[versions]
kotlin-test = "2.0.0"

[libraries]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.0.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.1" }
binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.14.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
